#################
### AUTOSTART ###
#################

exec-once = hyprsunset -t 3000
exec-once = awww-daemon & ~/.config/scripts/wall.sh
exec-once = waybar
exec-once = swaync
exec-once = hyprctl dispatch workspace 3
exec-once = [workspace 1 silent] ghostty
exec-once = brave
